In [6]:
import numpy as np
import matplotlib.pyplot as plt

def ca_atoms_from_pdf(filepath):
    
    
    with open(filepath) as f:
    
        lines = f.readlines()
        relevant_lines = []
        coordinates = []

        for line in lines:
            line = line.split()
            if line[0] == "ATOM" and line[2] == "CA":
                relevant_lines.append(line)
    
    positions = []
    for line in relevant_lines:
        positions.append([float(line[6]), float(line[7]), float(line[8])])

    return positions

def calculate_distance(positions):

    distance_array = np.zeros(shape=(len(positions), len(positions)))

    for i, pos_i in enumerate(positions):
        for j, pos_j in enumerate(positions):
            if i > j:
                distance_array[i][j] = distance_array[j][i] # becaus it is symmetric
            else:
                dist = ((pos_i[0] - pos_j[0])**2 + (pos_i[1] - pos_j[1])**2 + (pos_i[2] - pos_j[2])**2 )**0.5
                distance_array[i][j] = dist

    return distance_array

def find_close_atoms(distance_array, threshold):
    separation_array = distance_array < threshold
    fig = plt.figure()
    ax = plt.axes()
    plt.imshow(separation_array, cmap="Blues")
    ax.set_title("HEJ imshow")
   # plt.show()
    dots_x = []
    dots_y = []
    dims = distance_array.shape
    print(dims)
    for i in range(dims[0]):
        for j in range(dims[1]):
            if distance_array[i][j] < threshold:
                dots_x.append(i)
                dots_y.append(j)

    fig2 = plt.figure()
    ax = plt.axes()
    plt.scatter(dots_x, dots_y, c="r", marker='D', s=5)
    ax.set_title("HEJ dots")
    plt.show()

    return separation_array

def find_domains(distance_array, threshold=10):
    separation_array = distance_array < threshold
    dims = separation_array.shape
    max_score = 0
    best_partion = None
    for i in range(dims[0]):
        #for j in range(dims[1]):
        internal_a = np.sum(separation_array[0:i][0:i])
        internal_b = np.sum(separation_array[i+1:][i+1:])
        external = np.sum(separation_array[0:i][i+1:]) + np.sum(separation_array[i+1:][0:i])
        score = (internal_a / external) * (internal_b / external)
        print(internal_a, internal_b, external, score)
        if score > max_score:
            max_score = score
            best_partion = i
    print(separation_array[100+1:][100+1:])
    print(f"BEST PARTIONING IS {best_partion}")
    print(np.sum(internal_a))
    print("boolean",np.sum([True, True, False, False]))

positions = ca_atoms_from_pdf("1cdh.pdb")
distance_array = calculate_distance(positions)
separation_array = find_close_atoms(distance_array, threshold=8)
find_domains(distance_array, threshold=5)

print(separation_array)



        

(178, 178)


<Figure size 640x480 with 1 Axes>

<Figure size 640x480 with 1 Axes>

0 656 0 nan
2 648 4 81.0
6 640 8 60.0
10 633 11 52.31404958677686
14 625 16 34.1796875
18 618 19 30.814404432132964
22 611 23 25.410207939508506
25 604 26 22.337278106508876
29 597 28 22.08290816326531
34 591 31 20.909469302809573
37 583 33 19.808080808080806
41 574 41 14.0
44 567 43 13.492698756084371
48 559 48 11.645833333333334
51 551 52 10.392381656804734
55 545 56 9.558354591836734
58 539 58 9.293103448275861
62 532 62 8.580645161290322
65 524 66 7.819100091827365
68 517 71 6.974013092640348
71 511 74 6.6254565376187
74 504 75 6.6304
79 497 76 6.7976108033241
85 491 80 6.52109375
88 484 84 6.036281179138323
91 477 86 5.8689832341806385
95 471 89 5.648907966165888
99 463 92 5.4155245746691865
103 456 96 5.096354166666667
107 450 98 5.013536026655561
111 441 101 4.79864719145182
114 433 109 4.154700782762394
117 422 115 3.733383742911153
120 415 120 3.4583333333333335
123 406 124 3.247788761706556
127 398 130 2.9908875739644967
130 390 134 2.823568723546447
134 383 137 2.73440247216

/Users/emmarydholm/anaconda3/envs/py3/lib/python3.7/site-packages/ipykernel_launcher.py:73: RuntimeWarning: invalid value encountered in long_scalars
/Users/emmarydholm/anaconda3/envs/py3/lib/python3.7/site-packages/ipykernel_launcher.py:73: RuntimeWarning: divide by zero encountered in long_scalars


In [31]:
separation_array = distance_array < 8
dims = separation_array.shape
max_score = 0
best_partion = None
for i in range(dims[0]):
    #for j in range(dims[1]):
    internal_a = np.sum(separation_array[0:i,0:i])
    internal_b = np.sum(separation_array[i:,i:])
    external = np.sum(separation_array[0:i,i:]) + np.sum(separation_array[i:,0:i])
    score = (internal_a / external) * (internal_b / external)
    print(internal_a, internal_b, external, score)
    if score > max_score:
        max_score = score
        best_partion = i
print(separation_array[100+1:][100+1:])
print(f"BEST PARTIONING IS {best_partion}")
print(np.sum(internal_a))
print("boolean",np.sum([True, True, False, False]))


0 1902 0 nan
1 1889 12 13.118055555555554
4 1878 20 18.78
9 1861 32 16.3564453125
14 1844 44 13.334710743801653
19 1825 58 10.307669441141497
24 1802 76 7.48753462603878
29 1783 90 6.3835802469135805
34 1764 104 5.5451183431952655
39 1751 112 5.443957270408163
48 1740 114 6.426592797783933
57 1725 120 6.828125
64 1712 126 6.901486520534139
69 1699 134 6.5287926041434625
76 1686 140 6.537551020408163
81 1673 148 6.18667823228634
86 1656 160 5.563124999999999
91 1645 166 5.432392219480331
96 1632 174 5.174791914387633
101 1623 178 5.1736838782981955
106 1612 184 5.0470226843100185
111 1603 188 5.03431982797646
118 1590 194 4.985120629184822
125 1575 202 4.824894618174689
134 1562 206 4.932321613724197
139 1545 218 4.518874673849003
144 1526 232 4.082639714625446
149 1505 248 3.64602302289282
154 1482 266 3.225563909774436
159 1459 284 2.876177841698076
164 1438 300 2.6203555555555553
169 1423 310 2.502466181061394
176 1418 308 2.6307977736549164
185 1413 304 2.8285686461218833
196 1406 3

/Users/emmarydholm/anaconda3/envs/py3/lib/python3.7/site-packages/ipykernel_launcher.py:10: RuntimeWarning: invalid value encountered in long_scalars
  # Remove the CWD from sys.path while we load stuff.
/Users/emmarydholm/anaconda3/envs/py3/lib/python3.7/site-packages/ipykernel_launcher.py:10: RuntimeWarning: divide by zero encountered in long_scalars
  # Remove the CWD from sys.path while we load stuff.


In [9]:
distance_array

array([[ 0.        ,  3.82669048,  6.61477838, ..., 43.30909302,
        46.69507352, 49.67190061],
       [ 3.82669048,  0.        ,  3.81990798, ..., 40.28006284,
        43.66231184, 46.65386996],
       [ 6.61477838,  3.81990798,  0.        , ..., 36.74659278,
        40.1237831 , 43.1181913 ],
       ...,
       [43.30909302, 40.28006284, 36.74659278, ...,  0.        ,
         3.79906844,  6.385816  ],
       [46.69507352, 43.66231184, 40.1237831 , ...,  3.79906844,
         0.        ,  3.75494141],
       [49.67190061, 46.65386996, 43.1181913 , ...,  6.385816  ,
         3.75494141,  0.        ]])

In [13]:
separation_array[10+1:][10+1:].shape

(156, 178)

In [14]:
separation_array.shape

(178, 178)

In [21]:
a = np.arange(100).reshape(10,10)
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [30]:
a[5:, 5:]

array([[55, 56, 57, 58, 59],
       [65, 66, 67, 68, 69],
       [75, 76, 77, 78, 79],
       [85, 86, 87, 88, 89],
       [95, 96, 97, 98, 99]])

In [54]:
a[:5, :5] == a[0:5, 0:5] 

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [52]:
all_atoms = np.arange(dims[0])
U = all_atoms[0:int(dims[0]/2)]
V = all_atoms[int(dims[0]/2):]

best_contact = dims[0]


#external_links = [separation_array[], ]
for u in U:
    link_to_V = np.sum(separation_array[u,V])




In [38]:
link_to_V

2

In [39]:
separation_array[u,V]

array([ True,  True, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False])

In [44]:
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [46]:
a[1,np.arange(6)]

array([10, 11, 12, 13, 14, 15])

In [48]:
split_index = int(dims[0]/2)
U = [x for x in range(split_index)]
V = [x for x in range(split_index, dims[0])]

In [49]:
U

[0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49,
 50,
 51,
 52,
 53,
 54,
 55,
 56,
 57,
 58,
 59,
 60,
 61,
 62,
 63,
 64,
 65,
 66,
 67,
 68,
 69,
 70,
 71,
 72,
 73,
 74,
 75,
 76,
 77,
 78,
 79,
 80,
 81,
 82,
 83,
 84,
 85,
 86,
 87,
 88]

In [50]:
V

[89,
 90,
 91,
 92,
 93,
 94,
 95,
 96,
 97,
 98,
 99,
 100,
 101,
 102,
 103,
 104,
 105,
 106,
 107,
 108,
 109,
 110,
 111,
 112,
 113,
 114,
 115,
 116,
 117,
 118,
 119,
 120,
 121,
 122,
 123,
 124,
 125,
 126,
 127,
 128,
 129,
 130,
 131,
 132,
 133,
 134,
 135,
 136,
 137,
 138,
 139,
 140,
 141,
 142,
 143,
 144,
 145,
 146,
 147,
 148,
 149,
 150,
 151,
 152,
 153,
 154,
 155,
 156,
 157,
 158,
 159,
 160,
 161,
 162,
 163,
 164,
 165,
 166,
 167,
 168,
 169,
 170,
 171,
 172,
 173,
 174,
 175,
 176,
 177]